/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.research;

import com.evolutionary.Genetic;
import javax.swing.JFrame;

/**
 *
 * @author zulu
 */
public class ResearchMenu extends javax.swing.JFrame {
    
     //main meno of this frame
    JFrame mainMenu;

    /**
     * Creates new form ResearchMenu
     */
    public ResearchMenu() {
        initComponents();
    }
    
     public ResearchMenu(JFrame mainMenu) {         
        initComponents();
        this.setLocationRelativeTo(mainMenu);
        this.mainMenu = mainMenu;
        this.setTitle(Genetic.VERSION);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRealCodedRecombination = new javax.swing.JButton();
        btRealCodedMutation = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btRealCodedRecombination.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Research_128.png"))); // NOI18N
        btRealCodedRecombination.setText("Real Coded Recombination");
        btRealCodedRecombination.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRealCodedRecombination.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btRealCodedRecombination.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRealCodedRecombination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealCodedRecombinationActionPerformed(evt);
            }
        });

        btRealCodedMutation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Research_128.png"))); // NOI18N
        btRealCodedMutation.setText("Real Coded Mutation");
        btRealCodedMutation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRealCodedMutation.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btRealCodedMutation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRealCodedMutation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealCodedMutationActionPerformed(evt);
            }
        });

        btMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Main_Menu-128.png"))); // NOI18N
        btMenu.setText("Menu");
        btMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btRealCodedRecombination, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btRealCodedMutation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRealCodedRecombination)
                    .addComponent(btRealCodedMutation))
                .addGap(26, 26, 26)
                .addComponent(btMenu)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRealCodedRecombinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealCodedRecombinationActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new ReserachRecombination().setVisible(true);
            }
        });
    }//GEN-LAST:event_btRealCodedRecombinationActionPerformed

    private void btRealCodedMutationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealCodedMutationActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReserachMutation().setVisible(true);
            }
        });
    }//GEN-LAST:event_btRealCodedMutationActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        mainMenu.setLocationRelativeTo(this);
        this.dispose();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_btMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResearchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResearchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResearchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResearchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResearchMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btRealCodedMutation;
    private javax.swing.JButton btRealCodedRecombination;
    // End of variables declaration//GEN-END:variables
}
